# Generated by Django 3.2.8 on 2021-11-01 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211031_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atracao',
        ),
    ]
